(()=>{'use strict';const $=s=>document.querySelector(s);const designs={square:{name:'The Square',file:'assets/square-clock.png',caption:'01 / THE SQUARE'},round:{name:'The Round',file:'assets/round-clock.png',caption:'02 / THE ROUND'}};let selected='square';const dialog=$('#photo-dialog');function select(key){selected=key;const d=designs[key];$('#selected-name').textContent=d.name;$('#selected-image').src=d.file;$('#selected-image').alt=d.name+' floral clock product visual';$('#selected-caption').textContent=d.caption;document.querySelectorAll('[data-shape]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.shape===key)));$('#copy-status').textContent=''}function openPhoto(key){const d=designs[key];$('#dialog-title').textContent=d.name;$('#dialog-image').src=d.file;$('#dialog-image').alt='Enlarged '+d.name+' floral clock product visual';dialog.showModal()}document.querySelectorAll('[data-shape]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.shape)));document.querySelectorAll('[data-select]').forEach(b=>b.addEventListener('click',()=>{select(b.dataset.select);$('#choose').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}));document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>openPhoto(b.dataset.photo)));$('#selected-enlarge').addEventListener('click',()=>openPhoto(selected));$('#photo-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});$('#copy').addEventListener('click',async()=>{const text='TILE TIME / '+designs[selected].name+'\nColourful floral clock · Wood-tone frame · Gold-tone hands\nSize, materials, price and availability: please confirm with the seller.';try{await navigator.clipboard.writeText(text);$('#copy-status').textContent=designs[selected].name+' details copied.'}catch{$('#copy-status').textContent=text+' (Select this text to copy.)'}})})();

(()=>{'use strict';
const video=document.querySelector('#opening-video'),button=document.querySelector('#film-toggle'),status=document.querySelector('#film-status');
const portrait=matchMedia('(max-width: 700px) and (orientation: portrait)'),reduce=matchMedia('(prefers-reduced-motion: reduce)');
let userPaused=reduce.matches,inView=true,revision=0;
video.muted=true;
function label(){button.textContent=video.paused?'▷':'Ⅱ';button.setAttribute('aria-label',video.paused?'Play background animation':'Pause background animation')}
function sync(){if(userPaused||!inView||document.hidden){video.pause();return}const token=revision;video.play().then(()=>{if(token!==revision||userPaused||!inView||document.hidden)video.pause()}).catch(e=>{if(e.name!=='AbortError'&&!userPaused&&inView){status.textContent='Select the play button to watch the animation.'}label()})}
function source(){revision++;video.pause();video.src=portrait.matches?'assets/clock-mobile.mp4':'assets/clock-desktop.mp4';status.textContent='';video.load()}
button.addEventListener('click',()=>{userPaused=!video.paused;status.textContent='';sync()});
video.addEventListener('play',()=>{status.textContent='';label()});video.addEventListener('pause',label);video.addEventListener('canplay',sync);
video.addEventListener('error',()=>{status.textContent='The film could not load. Select the play button to retry.';label()});
button.addEventListener('click',()=>{if(video.error){userPaused=false;source()}});
new IntersectionObserver(entries=>{inView=entries[0].isIntersecting;sync()},{threshold:.1}).observe(video);
document.addEventListener('visibilitychange',sync);portrait.addEventListener('change',source);reduce.addEventListener('change',()=>{userPaused=reduce.matches;sync()});label();source();
})();
